//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondominioWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Propietario", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Propietario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ap_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ap_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ap_materno {
            get {
                return this.Ap_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ap_maternoField, value) != true)) {
                    this.Ap_maternoField = value;
                    this.RaisePropertyChanged("Ap_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ap_paterno {
            get {
                return this.Ap_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ap_paternoField, value) != true)) {
                    this.Ap_paternoField = value;
                    this.RaisePropertyChanged("Ap_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarPropietarioByID", ReplyAction="http://tempuri.org/IService/BuscarPropietarioByIDResponse")]
        CondominioWeb.ServiceReference1.Propietario BuscarPropietarioByID(int id_propietario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarPropietarioByID", ReplyAction="http://tempuri.org/IService/BuscarPropietarioByIDResponse")]
        System.Threading.Tasks.Task<CondominioWeb.ServiceReference1.Propietario> BuscarPropietarioByIDAsync(int id_propietario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CondominioWeb.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CondominioWeb.ServiceReference1.IService>, CondominioWeb.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CondominioWeb.ServiceReference1.Propietario BuscarPropietarioByID(int id_propietario) {
            return base.Channel.BuscarPropietarioByID(id_propietario);
        }
        
        public System.Threading.Tasks.Task<CondominioWeb.ServiceReference1.Propietario> BuscarPropietarioByIDAsync(int id_propietario) {
            return base.Channel.BuscarPropietarioByIDAsync(id_propietario);
        }
    }
}
